version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: prompt-hub-db
    environment:
      POSTGRES_DB: prompt_hub
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: 