version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: prompt-hub-db
    environment:
      POSTGRES_DB: prompt_hub
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - prompt-hub-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: prompt-hub-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@prompthub.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - prompt-hub-network

volumes:
  postgres_data:
  pgadmin_data:

networks:
  prompt-hub-network:
    driver: bridge 